package com.loyalty_program_app.backend.service.staff.impl;

import com.loyalty_program_app.backend.dto.staff.StaffCreateCustomerRequest;
import com.loyalty_program_app.backend.dto.user.UserResponse;
import com.loyalty_program_app.backend.dto.user.UserUpdateRequest;
import com.loyalty_program_app.backend.enums.Gender;
import com.loyalty_program_app.backend.enums.Role;
import com.loyalty_program_app.backend.enums.Tier;
import com.loyalty_program_app.backend.model.User;
import com.loyalty_program_app.backend.repository.UserRepository;
import com.loyalty_program_app.backend.service.staff.StaffCustomerService;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.*;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class StaffCustomerServiceImpl implements StaffCustomerService {

    private final UserRepository userRepository;
    private final BCryptPasswordEncoder passwordEncoder;

    @Override
    public UserResponse createCustomer(UUID staffId, StaffCreateCustomerRequest request) {

        if (userRepository.existsByEmail(request.getEmail())) {
            throw new RuntimeException("Email already registered");
        }

        User staff = userRepository.findById(staffId)
                .orElseThrow(() -> new RuntimeException("Staff not found"));

        User customer = new User();
        customer.setName(request.getName());
        customer.setEmail(request.getEmail());
        customer.setPhone(request.getPhone());
        customer.setPassword(passwordEncoder.encode(request.getPassword()));
        customer.setRole(Role.ROLE_CUSTOMER);
        customer.setGender(request.getGender() != null ? Gender.valueOf(request.getGender()) : Gender.NOT_SPECIFIED);
        customer.setTier(Tier.SILVER);
        customer.setPoints(0);
        customer.setActive(true);
        customer.setCreatedBy(staff.getId());

        // referralCode: can be generated by some util; for now simple email prefix
        if (customer.getReferralCode() == null) {
            customer.setReferralCode("CUST-" + System.currentTimeMillis());
        }

        userRepository.save(customer);
        return toDto(customer);
    }

    @Override
    public UserResponse updateCustomer(UUID staffId, UUID customerId, UserUpdateRequest request) {
        User customer = userRepository.findById(customerId)
                .orElseThrow(() -> new RuntimeException("Customer not found"));

        if (customer.getRole() != Role.ROLE_CUSTOMER) {
            throw new RuntimeException("Not a customer");
        }

        if (request.getName() != null) customer.setName(request.getName());
        if (request.getEmail() != null) customer.setEmail(request.getEmail());
        if (request.getPhone() != null) customer.setPhone(request.getPhone());
        if (request.getGender() != null) customer.setGender(Gender.valueOf(request.getGender()));
        if (request.getPassword() != null && !request.getPassword().isBlank()) {
            customer.setPassword(passwordEncoder.encode(request.getPassword()));
        }

        customer.setUpdatedBy(staffId);

        userRepository.save(customer);
        return toDto(customer);
    }

    @Override
    public void deactivateCustomer(UUID staffId, UUID customerId) {
        User customer = userRepository.findById(customerId)
                .orElseThrow(() -> new RuntimeException("Customer not found"));

        if (customer.getRole() != Role.ROLE_CUSTOMER) {
            throw new RuntimeException("Not a customer");
        }

        customer.setActive(false);
        customer.setUpdatedBy(staffId);
        userRepository.save(customer);
    }

    @Override
    public UserResponse getCustomer(UUID customerId) {
        User customer = userRepository.findById(customerId)
                .orElseThrow(() -> new RuntimeException("Customer not found"));
        return toDto(customer);
    }

    @Override
    public Page<UserResponse> searchCustomers(String search, Boolean active, Pageable pageable) {
        List<User> allCustomers = userRepository.findByRole(Role.ROLE_CUSTOMER);

        List<UserResponse> filtered = allCustomers.stream()
                .filter(u -> search == null ||
                        u.getName().toLowerCase().contains(search.toLowerCase()) ||
                        u.getEmail().toLowerCase().contains(search.toLowerCase()))
                .filter(u -> active == null || u.isActive() == active)
                .map(this::toDto)
                .toList();

        int start = (int) pageable.getOffset();
        int end = Math.min(start + pageable.getPageSize(), filtered.size());
        List<UserResponse> content = start > end ? List.of() : filtered.subList(start, end);

        return new PageImpl<>(content, pageable, filtered.size());
    }

    private UserResponse toDto(User user) {
        UserResponse dto = new UserResponse();
        dto.setId(user.getId());
        dto.setName(user.getName());
        dto.setEmail(user.getEmail());
        dto.setPhone(user.getPhone());
        dto.setImage(user.getImage());
        dto.setGender(user.getGender() != null ? user.getGender().name() : null);
        dto.setRole(user.getRole().name());
        dto.setTier(user.getTier() != null ? user.getTier().name() : null);
        dto.setPoints(user.getPoints());
        dto.setReferralCode(user.getReferralCode());
        dto.setActive(user.isActive());
        return dto;
    }
}
